version: '3'
services:
  fsenketo:
    image: qlands/fsenketo:1.86.2
    container_name: fsenketo
    networks:
      fsenketo:
        ipv4_address: 172.29.1.1
    environment:
      ENKETO_SRC_DIR: /srv/src/enketo_express
    ports:
      - 8005:8005
  fsredis:
    image: redis:5
    container_name: fsredis_main
    networks:
      fsenketo:
        ipv4_address: 172.29.1.2
  fsredis2:
    image: redis:5
    container_name: fsredis_cache
    networks:
      fsenketo:
        ipv4_address: 172.29.1.3
networks:
  fsenketo:
     ipam:
        driver: default
        config:
          - subnet: 172.29.0.0/16
